# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcJCzri_SX65j1Dpay0eZKk-3rmWhIim
"""

def calculator():
    while True:
        print("\n=== Simple Calculator ===")
        print("Choose an operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Exit")


        operation = input("Enter your choice (1-5): ")

        if operation == '5':
            print("Exiting the calculator. Goodbye!")
            break

        try:
            num1 = float(input("Enter the first number: "))
            num2 = float(input("Enter the second number: "))


            if operation == '1':
                result = num1 + num2
                print(f"The result of addition is: {result}")
            elif operation == '2':
                result = num1 - num2
                print(f"The result of subtraction is: {result}")
            elif operation == '3':
                result = num1 * num2
                print(f"The result of multiplication is: {result}")
            elif operation == '4':
                if num2 != 0:
                    result = num1 / num2
                    print(f"The result of division is: {result}")
                else:
                    print("Error: Division by zero is not allowed.")
            else:
                print("Invalid operation choice. Please select a valid option.")
        except ValueError:
            print("Invalid input. Please enter numeric values.")


calculator()