# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rcJCzri_SX65j1Dpay0eZKk-3rmWhIim
"""

import random
import string

def generate_password():
    print("Welcome to the Password Generator!")


    try:
        length = int(input("Enter the desired length of the password: "))
        if length <= 0:
            print("Please enter a positive number.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return


    print("\nChoose the complexity level:")
    print("1. Numbers only")
    print("2. Letters only")
    print("3. Letters and numbers")
    print("4. Letters, numbers, and special characters")

    try:
        complexity = int(input("Enter your choice (1-4): "))
        if complexity not in [1, 2, 3, 4]:
            print("Invalid choice. Please enter a number between 1 and 4.")
            return
    except ValueError:
        print("Invalid input. Please enter a number.")
        return


    if complexity == 1:
        char_pool = string.digits
    elif complexity == 2:
        char_pool = string.ascii_letters
    elif complexity == 3:
        char_pool = string.ascii_letters + string.digits
    elif complexity == 4:
        char_pool = string.ascii_letters + string.digits + string.punctuation


    password = ''.join(random.choice(char_pool) for _ in range(length))


    print("\nGenerated Password:", password)


generate_password()