# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zl8-X1H2aghTj6LVHOqn-U3FInUi_UGK
"""

class ToDoList:
    def __init__(self): # Change _init_ to __init__
        self.tasks = {}
        self.next_id = 1

    def add_task(self, task):
        self.tasks[self.next_id] = task
        print(f"Task '{task}' added successfully with ID: {self.next_id}")
        self.next_id += 1

    def update_task(self, task_id, new_task):
        if task_id in self.tasks:
            old_task = self.tasks[task_id]
            self.tasks[task_id] = new_task
            print(f"Task ID {task_id} updated from '{old_task}' to '{new_task}'")
        else:
            print(f"Task ID {task_id} not found.")

    def delete_task(self, task_id):
        if task_id in self.tasks:
            removed_task = self.tasks.pop(task_id)
            print(f"Task ID {task_id} ('{removed_task}') deleted successfully.")
        else:
            print(f"Task ID {task_id} not found.")

    def list_tasks(self):
        if not self.tasks:
            print("No tasks in the list.")
        else:
            print("Current Tasks:")
            for task_id, task in self.tasks.items():
                print(f"ID {task_id}: {task}")


todo_list = ToDoList()
todo_list.add_task("Buy groceries")
todo_list.add_task("Read a book")
todo_list.list_tasks()
todo_list.update_task(1, "Buy groceries and cook dinner")
todo_list.delete_task(2)
todo_list.list_tasks()